apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
 name: ocs-storagecluster
 namespace: openshift-storage
spec:
 manageNodes: false
 resources:
   mds:
     limits:
       cpu: "3"
       memory: "8Gi"
     requests:
       cpu: "3"
       memory: "8Gi"
 monDataDirHostPath: /var/lib/rook
 storageDeviceSets:
 - count: 2  # <-- Modify count to desired value. For each set of 3 disks increment the count by 1.
   dataPVCTemplate:
     spec:
       accessModes:
       - ReadWriteOnce
       resources:
         requests:
           storage: "70Gi"  # <-- This should be changed as per storage size. Minimum 100 GiB and Maximum 4 TiB
       storageClassName: localblock
       volumeMode: Block
   name: ocs-deviceset
   placement: {}
   portable: false
   replica: 3
   resources:
     limits:
       cpu: "2"
       memory: "3Gi"
     requests:
       cpu: "2"
       memory: "3Gi"

